sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=standard
env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
